# Basic Information 
title: Tamara Gedankien 
position: Postdoctoral Research Scientist
affiliation: Columbia University
email: tamara.gedankien(at)columbia.edu

# Search Engine Optimization (SEO)
keywords: tamara gedankien, tgedankien, gedankient, gedankien
description: Tamara Gedankien is a postdoctoral research scientist at Columbia University.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Wu5XyXAAAAAJ&hl=en
github_link: https://github.com/tgedankien
linkedin: https://www.linkedin.com/in/tamara-gedankien-63a7a929/?locale=en_US
twitter: https://twitter.com/Gedankient

# Images 
avatar: ./assets/img/Gedankien_Headshot.jpg
favicon: ./assets/img/Gedankien_Headshot.jpg
# favicon_dark: ./assets/img/favicon-dark.png

# # Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
